version: 0.2

env:
  variables:
    # SDLC_ENVIRONMENT: "$1"
    DOCKER_IMAGE_NAME: "$1"
    # GIT_REPO: "https://git-codecommit.us-east-1.amazonaws.com/v1/repos/dockerecrtestbuild"
phases:
  install:
    commands:
      - apt-get update -y && apt-get install -y git
      - apt-get update -y && apt-get install -y dos2unix
  pre_build:
    commands:
      - echo "This is Codecommit Repo URL - $CODEBUILD_SOURCE_REPO_URL"
      - |
        REPO_NAME=$(echo "$CODEBUILD_SOURCE_REPO_URL" | awk -F "/" '{print $NF}')
        BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | awk -F "/" '{print $NF}')
        echo "BRANCH_NAME is : $BRANCH_NAME"
        echo "CODEBUILD_SOURCE_REPO_URL is : $CODEBUILD_SOURCE_REPO_URL"
        echo "CODEBUILD_SOURCE_VERSION is : $CODEBUILD_SOURCE_VERSION"
      - echo "This is Codecommit Repo Name - $REPO_NAME"
      - echo "This is the CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR"
      - echo "This is the commit id from Source Control - $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - chmod +x docker_python/scripts/build_and_push.sh

  build:
    commands:
      - echo "inside build commands and printing all environment variables below"
      - printenv
      - echo `pwd`
      - tr -d '\r' < docker_python/scripts/build_and_push.sh > clean_build.sh
      - bash -c "tr -d '\r' < docker_python/scripts/build_and_push.sh | bash" $DOCKER_IMAGE_NAME

